; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Set breakpoint mode
;build_flags =
;  -DAVR8_BREAKPOINT_MODE=2

; In a nutshell, avr-stub is a piece of software (stub)
; that is added to your application and communicates
; with PlatformIO when a debug session is running. 
; It requires several additional configuration steps 
; in order to use it as a debug tool. To use avr-stub, 
; the following settings
;debug_tool = avr-stub
;debug_port = SERIAL_PORT

; Where the value in debug_port is a serial port connected 
; to your board and jdolinay/avr-debugger is a special library
; that implements the GDB stub.
; GDB stub implementation
;lib_deps =
;    jdolinay/avr-debugger @ ~1.4
