; for 16-bit app support
[386Enh] ; for 16-bit app support
woafont=dosapp.fon
EGA80WOA.FON=EGA80WOA.FON
EGA40WOA.FON=EGA40WOA.FON
CGA80WOA.FON=
CGA40WOA.FON=CGA40WOA.FON

[drivers]
wave=mmdrv.dll
timer=3657

[mci]
