; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino

build_flags = 
    -std=gnu++17
    -Og                              ; Принудительно передаем GCC флаг оптимизации путей, чтобы always_inline сработал
    -Os                              ; Включает оптимизации -O2, кроме тех, что раздувают код
    -fno-exceptions                  ; Отключить исключения C++
    ;-fno-rtti                        ; Отключить RTTI (Run-Time Type Information)
    -ffunction-sections              ; Поместить каждую функцию в отдельную секцию
    -fdata-sections                  ; Поместить каждую глобальную переменную в отдельную секцию
    ;-fno-threadsafe-statics          ; Отключить защиту статических переменных в функциях
    ;-fno-enforce-eh-specs            ; Отключить генерацию кода для throw() спецификаций
    ;-fno-use-cxa-atexit              ; Отключить регистрацию деструкторов глобальных объектов
    -fno-non-call-exceptions         ; Гарантия, что исключения не будут генерироваться вообще
    -fno-asynchronous-unwind-tables  ; Убрать таблицы раскрутки стека
    -fno-ident                       ; Убрать служебные строки GCC из бинарника
    -fno-omit-frame-pointer          
    -fno-stack-protector             ; Отключить защиту стека (на AVR она бесполезна)    
    -Wl,--gc-sections                ; Удалить неиспользуемые секции  
    -Wl,--relax                      ; Позволить линкеру оптимизировать переходы и константы
    -Wl,--strip-all                  ; Удалить символы и таблицы отладки
    -Wl,--undefined=__vector_default ; Гарантирует, что пустые обработчики прерываний не будут тянуть лишний код
    -flto                            ; Включить LTO (даёт огромный выигрыш на AVR)
    -fuse-linker-plugin

build_unflags = 
    -std=gnu++11
    -fno-fat-lto-objects

[platformio]
; Перенаправляем глобальный поиск библиотек проекта на твою общую папку.
; Путь относительно этого файла: выйти на уровень вверх и зайти в uno_lib
lib_dir = ../uno_lib

